language: node_js
node_js:
- '6'

before_install:
  - stty cols 80

env:
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- npm install -g concurrently@3.1.0

script:
- npm run build

deploy:
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
